---
name: Build and release

on:
  release:
    types:
      - created
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Build
        uses: gradle/gradle-build-action@v3
        with:
          arguments: -Pversion=${{ github.head_ref || github.ref_name }} check shadowJar

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/watson.jar